Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Controllers/BookController.cs
using Assign4ErrorHandling.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assign4ErrorHandling.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
			throw new CustomApplicationException();
            return View();
        }
    }
}

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assign4ErrorHandling.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			throw new Exception();
			return View();
		}

		public ActionResult Logo()
		{
			return View("Index");
		}

	}
}

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assign4ErrorHandling.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
			throw new ArgumentException();
            return View();
        }
    }
}

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Views/Shared/ErrorArgument.cshtml
@{
    ViewBag.Title = "Movies";
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Movies</title>
</head>
<body>
	<hgroup>
		<h1>Error in Movies.</h1>
		<h2>You pressed Movies and i sent you here.</h2>
	</hgroup>
</body>
</html>

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Views/Shared/ErrorCustom.cshtml
@{
	ViewBag.Title = "Books";
}




<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Books</title>
</head>
<body>
	<hgroup>
		<h1>Error in Books.</h1>
		<h2>You pressed Books and i sent you here.</h2>
	</hgroup>
</body>
</html>

Vefforritun/visual studio/Assign4ErrorHandlingSolution/Assign4ErrorHandling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Error Handling Site", "Logo", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Front Page", "Index", "Home")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
                    <li>@Html.ActionLink("Books", "Index", "Book")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>